name: Deploy to Dokploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Private Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_REPO }}/test-app:latest

      - name: Trigger Dokploy Deployment via API
        env:
          DOKPLOY_API_TOKEN: ${{ secrets.DOKPLOY_API_TOKEN }}
          APPLICATION_ID: "7PIuOX-GntoB13JVs_w-h"
          DOKPLOY_HOST: "http://196.190.220.43:3000/"
          DOCKER_IMAGE: "${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_REPO }}:latest"
        run: |
          curl -X POST "$DOKPLOY_HOST/api/application.deploy" \
          -H "Authorization: Bearer $DOKPLOY_API_TOKEN" \
          -H "accept: application/json" \
          -d '{ "applicationId": "7PIuOX-GntoB13JVs_w-h" 
                "app": "ci-cd-demo",
                "image": "'${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_REPO }}:latest'",
                "ports": [
                  {
                    "host": 3001,
                    "container": 3000
                  }
                ]
              }'
